### ISSUE TITLE
 Build error with character encoding problem on mac osx maverick

### ISSUE THREAD

**Issue by channainfo** [richcarl/sendmail#2]
I got the following error when I built
 **Non-UTF-8 character(s) detected, but no encoding declared. Encode the file in UTF-8 or add "%% coding: latin-1" at the beginning of the file. Retrying with latin-1 encoding.**

As I understand the file is being encoded in UTF-8 but some non-UTF-8 characters are used 

**Håkan**, **åäö**

I am not really sure what is the best way to handle this. Please help ?

**Comment by richcarl** [comment]
Closing. See #3
